development:
  adapter: postgresql
  encoding: unicode
  database: videocontest
  host: localhost
  pool: 5
  timeout: 5000
  username: tjl
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: test_videocontest
  host: localhost
  pool: 5
  timeout: 5000
  username: tjl
  password:
